osindicados/jogo/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns

urlpatterns = patterns('osindicados.jogo.views',
  (r'^$', 'index'),
  (r'^partida/$', 'partida'),
  (r'^config/$', 'config'),
  (r'^responder/$', 'responder'),
  (r'^erro/$', 'erro'),
  (r'^ganhou/$', 'ganhou'),
  (r'^ajudaTroca/$', 'ajudaTroca'),
  (r'^ajudaElimina/$', 'ajudaElimina'),
  (r'^ajudaTempo/$', 'ajudaTempo'),
  (r'^horario/$', 'horario'),
  (r'^entrarRanking/$', 'entrarRanking'),
  (r'^ranking/$', 'ranking'),
  (r'^design/$', 'testedesign'),
  (r'^index/$', 'index'),
  (r'^comojogar/$', 'comojogar'),
)

osindicados/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       (r'^jogo/', include('osindicados.jogo.urls')),
                       (r'^admin/backup/', include('osindicados.backup.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^osindicadosmedia/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       (r'^$', include('osindicados.jogo.urls')),
                       (r'^backup/', include('osindicados.backup.urls')),
                       (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name':'admin/login.html'}),
                       )


osindicados/jogo/models.py
# -*- coding: utf-8 -*-
from django.db import models

DIFICULDADES = (
                    (1, 'Amador'),
                    (2, 'Profissional'),
                    (3, 'Celebridade'),
                    (4, 'Ídolo')
                )

class Tema(models.Model):

    def __init__(self, *args, **kwargs):
        super(Tema, self).__init__(*args, **kwargs)

    nome = models.CharField(max_length=30)
    nomeTrofeu = models.CharField(max_length=30)
    imagemTrofeu = models.CharField(max_length=100)
    def __unicode__(self):
        return self.nome

class Pergunta(models.Model):

    def __init__(self, *args, **kwargs):
        super(Pergunta, self).__init__(*args, **kwargs)

    enunciado = models.CharField(max_length=1000)
    altCorreta = models.CharField(max_length=200)
    altIncorreta1 = models.CharField(max_length=200)
    altIncorreta2 = models.CharField(max_length=200)
    altIncorreta3 = models.CharField(max_length=200)
    altIncorreta4 = models.CharField(max_length=200)
    dificuldade = models.IntegerField(choices=DIFICULDADES, null=True, blank=True)
    idAssunto = models.ForeignKey(Tema)
    def __unicode__(self):
        return self.enunciado

    @staticmethod
    def getPerguntaPorAssunto(assuntos, ids=[]):
        return Pergunta.objects.filter(idAssunto__nome__in=assuntos).exclude(id__in=ids).order_by('?')[:1][0]

    @staticmethod
    def getPerguntaPorIdsAssunto(idsAssunto, ids=[]):
        return Pergunta.objects.filter(idAssunto__in=idsAssunto).exclude(id__in=ids).order_by('?')[:1][0]

    @staticmethod
    def getPerguntasPartidaPorAssunto(assuntosPartida):
        return Pergunta.objects.filter(idAssunto__nome__in=assuntosPartida).order_by('?')[:25]

    @staticmethod
    def getPerguntasPartidaPorIdsAssunto(idsAssunto):
        return Pergunta.objects.filter(idAssunto__in=idsAssunto).order_by('?')[:25]

class Placar(models.Model):

    def __init__(self, *args, **kwargs):
        super(Placar, self).__init__(*args, **kwargs)
        if self.acertosEsporte is None:
            self.acertosEsporte = 0
        if self.acertosCinema is None:
            self.acertosCinema = 0
        if self.acertosMusica is None:
            self.acertosMusica = 0
        if self.acertosTelevisao is None:
            self.acertosTelevisao = 0
        if self.acertosCGerais is None:
            self.acertosCGerais = 0
        if self.acertosCiencias is None:
            self.acertosCiencias = 0

    nomeJogador = models.CharField(max_length=30)
    dificuldade = models.IntegerField(choices=DIFICULDADES)
    acertosEsporte = models.IntegerField()
    acertosCinema = models.IntegerField()
    acertosMusica = models.IntegerField()
    acertosTelevisao = models.IntegerField()
    acertosCGerais = models.IntegerField()
    acertosCiencias = models.IntegerField()

    def __unicode__(self):
        pontos = {'Esporte' : self.acertosEsporte,
                'Cinema' : self.acertosCinema,
                'Musica' : self.acertosMusica,
                'Televisao' : self.acertosTelevisao,
                'CGerais' : self.acertosCGerais,
                'Ciencias' : self.acertosCiencias,
                'Jogador' : self.nomeJogador,
                'Dificuldade' : self.dificuldade }
        return str(pontos)

osindicados/jogo/views.py
# -*- coding: utf-8 -*-

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from osindicados.jogo.models import DIFICULDADES, Tema, Pergunta, \
    Placar
from osindicados.jogo.partidaconfs import *
from osindicados.jogo.utils import sortearAlternativas, selectPlacares
import time
import random


temasjogo = ['Esporte', 'Cinema', u'Música', u'Televisão', 'Conhecimentos Gerais', u'Ciências']

def index(request):
    temas = Tema.objects.all()
    perguntas = Pergunta.objects.all()

    # calcula quantas perguntas foram cadastradas em cada tema
    list_tema_qntd = [(tema, len(Pergunta.objects.filter(idAssunto__exact=tema.id))) for tema in temas]

    return render_to_response('jogo/index.html', {'list_tema_qntd': list_tema_qntd, 'perguntas': perguntas})

def partida(request):
    """
    Pagina de "Responder Pergunta". Apos configurar o jogo, o usuario e' redirecionado para esta pagina.
    Busca uma nova pergunta e repassa a tela.
    """

    # Testa se já existe uma pergunta sendo respondida. Se houver, continua com a mesma. Assim, caso o usuário
    # atualize a página, ele não "ganha" uma ajuda de troca de graça.
    if 'pergunta' in request.session:
        return render_to_response('jogo/partida.html', {'confs': request.session['confs'], 'pergunta' : request.session['pergunta'], 'alternativas' : request.session.get('alternativas'), 'respondidas' : request.session.get('respondidas'), 'ajudas' : request.session.get('ajudas'), 'eliminadas' : request.session.get('eliminadas'), 'placar' : request.session.get('placar'), 'temasjogo' : temasjogo}, context_instance=RequestContext(request))

    # Testa se o usuário já passou pela tela de configuração. Se não passou, mostra mensagem de erro.
    if 'confs' in request.session:
        if 'p_ids' in request.session:
            # Nao e' a primeira pergunta. Recupera a lista de ids que ja' foram
            p_ids = request.session['p_ids']
            # Busca uma pergunta nao-repetida
            pergunta = Pergunta.getPerguntaPorAssunto(request.session['confs'].temas, p_ids)
            # Adiciona o id 'a lista
            p_ids.append(pergunta.id)
            # Guarda de volta na sessao
            request.session['p_ids'] = p_ids
        else:
            # E' a primeira pergunta. Busca uma pergunta com qualquer id.
            pergunta = Pergunta.getPerguntaPorAssunto(request.session['confs'].temas)
            # Inicia a lista de ids de perguntas com o id dessa pergunta
            p_ids = [pergunta.id]
            # Adiciona a lista 'a sessao
            request.session['p_ids'] = p_ids
            request.session['respondidas'] = 0


        mixed = sortearAlternativas(pergunta)

        request.session['pergunta'] = pergunta
        request.session['alternativas'] = mixed
        print "Eliminadas: ", request.session.get('eliminadas')

        return render_to_response('jogo/partida.html', {'confs': request.session['confs'], 'pergunta' : pergunta, 'alternativas' : mixed, 'respondidas' : request.session.get('respondidas'), 'ajudas' : request.session.get('ajudas'), 'eliminadas' : request.session.get('eliminadas'), 'placar' : request.session.get('placar'), 'temasjogo' : temasjogo}, context_instance=RequestContext(request))
    # Usuário ainda não configurou a partida
    else:
        return HttpResponse("Vc ainda nao configurou sua partida.")

def config(request):
    """
    Configurações do jogo, é a tela inicial do sistema inteiro
    O request deve conter o tema e a dificuldade
    """
    if request.POST.getlist('temas') and 'dificuldade' in request.POST:
        print 'tem tema e dificuldade'
        # Cria um novo objeto passando as opções do usuário
        conf = Partidaconfs(request.POST['dificuldade'], request.POST.getlist('temas'))

        # Coloca na sessão
        request.session.clear()
        request.session['confs'] = conf

        # Inicializa as ajudas de acordo com a dificuldade
        # são três para o nível amador(1), duas para profissional(2), uma para celebridade(3) e nenhuma vez para ídolo(4)
        numajudas = 3 #amador
        if request.POST['dificuldade'] == '31':
            numajudas = 0 # ídolo
        if request.POST['dificuldade'] == '21':
            numajudas = 1 # celebridade
        if request.POST['dificuldade'] == '11':
            numajudas = 2 # profissional
        ajudas = {'troca' : numajudas, 'elimina' : numajudas, 'tempo' : numajudas}
        request.session['ajudas'] = ajudas

        # Inicializa Placar()
        placar = Placar()
        request.session['placar'] = placar

        return HttpResponseRedirect(reverse('osindicados.jogo.views.partida'))
    if not(request.POST.getlist('temas')) and ('dificuldade' in request.POST):
        print "nao tem tema, mas tem dificuldade"
        return render_to_response('jogo/config.html', {'dificuldades': DIFICULDADES, 'temas' : Tema.objects.all(), 'error' : 'Por Favor, escolha um tema' }, context_instance=RequestContext(request))
    
    print "não tem nada!"
    return render_to_response('jogo/config.html', {'dificuldades': DIFICULDADES, 'temas' : Tema.objects.all() }, context_instance=RequestContext(request))

def responder(request):
    """
    Executado quando o usuário responde uma pergunta.
    O request deve conter a resposta dada pelo usuário e o id da pergunta.
    """
    # Verificacao de tempo
    
    hr_inicio = request.session.get('hr_inicio')
    print "Sessao", request.session
    print hr_inicio
    
    horarioInicio = float(request.session['hr_inicio']) # Horario em que o timer foi iniciado
    horarioFim = float(request.POST['hr']) # Horario em que o form foi submetido

    if 'hr_extensao' in request.session:
        # Se houve extensao, o usuario teve 60 segundos para responder
        horarioFimTeorico = horarioInicio + 60
        del request.session['hr_extensao']
        #del request.session['hr_inicio']
    else:
        # Se nao houve extensao, o usuario teve so 30 segundos para responder
        horarioFimTeorico = horarioInicio + 30

    # Informacao de debug
    print (horarioFim - horarioInicio)
    print (horarioFim - horarioFimTeorico)

    # Tolerancia maxima de 1 segundo de diferenca entre o esperado e o real
    if (horarioFim - horarioFimTeorico) > 1:
        request.session.clear()
        return HttpResponseRedirect(reverse('osindicados.jogo.views.erro'))

    # Passou pela verificacao de tempo. Comeca a logica da resposta.

    altSelecionada = request.POST["alternativa"]

    if 'respondidas' not in request.session:
        request.session['respondidas'] = 0

    if 'pergunta' in request.session:
        pergunta = request.session['pergunta']

        # Retira a pergunta da sessão. Necessário pois a view Partida só carrega uma pergunta nova se não houver nenhuma na sessão.
        del request.session['pergunta']

        # Retira a lista de eliminadas tb (importante caso 2 perguntas tenham alternativas iguais)
        if 'eliminadas' in request.session:
            del request.session['eliminadas']

        if pergunta.altCorreta == altSelecionada:
            if int(request.session['respondidas']) == 4:
                # Respondeu a ultima pergunta corretamente. Fim de jogo.quer
                # Atualiza o placar antes.
                request.session['placar'] = incrementarPlacar(request.session['placar'], pergunta)
                return HttpResponseRedirect(reverse('osindicados.jogo.views.ganhou'))
            else:
                # Respondeu certo, mas nao eh a ultima
                # Atualiza o placar
                request.session['placar'] = incrementarPlacar(request.session['placar'], pergunta)
                # Atualiza o numero de perguntas respondidas
                request.session['respondidas'] = int(request.session['respondidas']) + 1
                return HttpResponseRedirect(reverse('osindicados.jogo.views.partida'))
        else:
            #Respondeu errado. Fim de jogo.
            request.session.clear()
            return HttpResponseRedirect(reverse('osindicados.jogo.views.erro'))


def erro(request):
    """
    Executado quando o usuário erra uma pergunta, quando o tempo esgota ou quando se verifica que o usuário
    está trapaceando (por exemplo, alterar o timer da tela).
    """
    return render_to_response('jogo/erro.html')

def ganhou(request):
    """
    Executado quando o usuário ganha a partida (25 respostas corretas)
    """
    return render_to_response('jogo/ganhou.html', context_instance=RequestContext(request))

def ajudaTroca(request):
    """
    Executado quando o usuário solicita a ajuda de troca de pergunta.
    Verifica se o usuário ainda pode solicitar esta ajuda e, caso possa, retira da sessão a pergunta atual e
    redireciona à tela de partida
    """
    # Verifica se o usuário tem mesmo uma ajuda de troca.
    ajudas = request.session['ajudas']
    trocas = int(ajudas['troca'])
    if trocas > 0:
        # Diminui uma ajuda de troca
        ajudas['troca'] = trocas - 1
        request.session['ajudas'] = ajudas
        # Retira a pergunta da sessão, para poder trocar
        del request.session['pergunta']
        # Retira a lista de eliminadas tb (importante caso 2 perguntas tenham alternativas iguais)
        if 'eliminadas' in request.session:
            del request.session['eliminadas']
        # Volta à tela de partida
        return HttpResponseRedirect(reverse('osindicados.jogo.views.partida'))
    # Não tinha uma ajuda.
    else:
        return HttpResponse("Voce est&aacute; roubando...")

def ajudaElimina(request):
    """
    Executado quando o usuário solicita uma ajuda de eliminação de alternativas.

osindicados/templates/jogo/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <script type="text/javascript" src="/osindicadosmedia/js/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="/osindicadosmedia/js/jquery.countdown.js"></script>
    <script type="text/javascript" src="/osindicadosmedia/js/jquery.countdown-pt-BR.js"></script>
    <script type="text/javascript" src="/osindicadosmedia/js/javascript.js"></script>
    <script type="text/javascript" src="/osindicadosmedia/js/jquery-ui-1.8.2.custom.min.js"></script>
    
    <link rel="stylesheet" href="/osindicadosmedia/css/jquery.countdown.css" />
    <link rel="stylesheet" href="/osindicadosmedia/css/partida.css" />
    <link rel="stylesheet" href="/osindicadosmedia/css/jquery-ui-1.8.2.custom.css" />
    
    <title>Os Indicados</title>
</head>

<body>
    <div id="background">
        <div id="tela">
            {% block tela %}{% endblock %}
        </div>
        <div id="sidebar">
            {% block sidebar %}{% endblock %}
        </div>
        <div id="footer">
            {% block footer %}{% endblock %}
        </div>
    </div>
</body>
</html>

osindicados/templates/jogo/basedesign.html
<html>
<head>
    <script type="text/javascript" src="/osindicadosmedia/js/jquery-1.4.2.min.js"></script>
    <link rel="stylesheet" href="/osindicadosmedia/css/base.css" />
	<script type="text/javascript" src="/osindicadosmedia/js/jquery-ui-1.8.2.custom.min.js"></script>
    <link rel="stylesheet" href="/osindicadosmedia/css/jquery-ui-1.8.2.custom.css" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    {% block extrahead %}{% endblock %}
    <title>Os Indicados</title>
</head>

<body>
	<div id="background">
	    <div id="tela">
	        {% block tela %}{% endblock %}
	    </div>
	    <div id="sidebar">
	    	{% block sidebar %}{% endblock %}
	    </div>
	    <div id="footer">
	    	{% block footer %}{% endblock %}
	    </div>
    </div>
</body>
</html>


osindicados/templates/jogo/comojogar.html
{% extends "jogo/basedesign.html" %}

{% block extrahead %}
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script type="text/javascript">
$(function(){
	$("a").button();
})
</script>
<style type="text/css">
#background{
	position: absolute;
	left: 10%;
	/* TODO: Mudar os tamanhos quando mudar a imagem*/
	width: 1000px;
	height: 7110px;
	background-image: url("/osindicadosmedia/img/tv.png");
	background-repeat: no-repeat;
	}
</style>
{% endblock extrahead %}

{% block tela %}


<div style="text-align: justify; padding-left: 50px; padding-right: 50px; margin-top:30px; margin-bottom:30px; width:490px; height:380px; overflow: auto;"; align="left">
<br/><br/><br/><br>
<h1><img alt="como jogar" src="/osindicadosmedia/img/doubt.png"> Como jogar  </h1> <br/>

Este &eacute; um jogo de perguntas e respostas.
<br><br>
Antes de jogar, voc&ecirc; deve selecionar quais dos temas voc&ecirc; deseja que sejam abordados nas perguntas, clicando em "Esporte", "Cinema", "M&uacute;sica", "Televis&atilde;o", "Conhecimentos Gerais" e "Ci&ecirc;cias". O s&iacute;mbolo verde indica um tema selecionado.
<br><br>
<center><img alt="como jogar" src="/osindicadosmedia/img/temas.png"></center>
<br>
Em seguida, &eacute; preciso escolher o n&iacute;vel das perguntas: "Amador", "Profissional", "Celebridade" ou "&Iacute;dolo", sendo a categoria "Amador" a que apresenta perguntas mais f&aacute;ceis e a categoria "&Iacute;dolo" a que apresenta as mais dif&iacute;ceis. Para mudar de n&iacute;vel, utilize as setas.
<br><br>
<center><img alt="como jogar" src="/osindicadosmedia/img/niveis.png"></center>
<br>
Para iniciar, clique em "Iniciar Partida". A primeira pergunta ser&aacute; mostrada na tela. Voc&ecirc; ter&aacute; 25 segundos para respond&ecirc;-la, selecionando uma alternativa e clicando em "responder". Para vencer neste jogo, &eacute; preciso responder 25 perguntas (sobre os temas selecionados) sem cometer nenhum erro. No topo da p&aacute;gina pode ser visto o n&uacute;mero da pergunta e a categoria a qual ela pertence e do lado direito da pergunta pode ser visto o n&uacute;mero de perguntas respondidas de cada tema at&eacute; o momento. Tamb&eacute; a direita, v&ecirc;-se os temas selecionados, o n&iacute;vel de dificuldade selecionado e o bot&atilde;o "Iniciar Nova Partida", que retorna para a p&aacute;gina inicial;
<br><br>
<center><img alt="como jogar" src="/osindicadosmedia/img/perguntas.png"></center>
<br>
Em todas as perguntas, existem 3 tipos de ajuda: "Troca de perguntas" (desconsidera-se a pergunta atual e mostra um nova pergunta), "Elimina 2 alternativas" (2 alernativas de resposta <i>incorretas</i> s&atilde;o assinaladas) e "Incrementa tempo" (adiciona-se 30 segundos ao tempo para a pergunta ser respondida). &Eacute; poss&iacute;vel usar no m&aacute;ximo 3 vezes cada uma das ajudas durante todo o jogo.
<br><br>
<center><img alt="como jogar" src="/osindicadosmedia/img/helpes.png"></center>
<br>
Caso alguma pergunta seja respondida de forma incorreta, o jogo ser&aacute; finalizado e, para retornar ao jogo, deve-se clicar em "Voltar para a Tela Inicial". Se conseguir competar o jogo respondendo todas as perguntas corretamente, ser&aacute; poss&iacute;vel inserir seu nome no ranking. O ranking est&aacute; dispon&iacute;vel na tela inicial, clicando-se em "Ver Ranking".
<br><br>
Boa sorte!
<br><br>
</div>

<center> <a href="../config/">Voltar para Tela Inicial</a> </center>
{% endblock tela %}

osindicados/templates/jogo/config.html
{% extends "jogo/basedesign.html" %}

{% block extrahead %}
<script language="javascript" type="text/javascript">
<!--
	i = 0;
	dificuldade = [
	{% for n, v in dificuldades %}
	'{{ v }}',
	{% endfor %}
	]

	function selectDifi(option) {
	    if(option == 'left') {
	        if(i == 0);
	        else i--;
	        document.getElementById('listdificuldades').value = dificuldade[i];
	        document.getElementById('dificuldade').value = '' + i + 1;
	    } else {
	    	if (i==3);
	        else i ++;
	        document.getElementById('listdificuldades').value = dificuldade[i];
	        document.getElementById('dificuldade').value = '' + i + 1;
	    }

	}
// -->
</script>

<script type="text/javascript">
	$(function() {
		$(".check").button({
            icons: {
               primary: 'ui-icon-circle-check'}
           });
		$("button, input:submit, a").button();
	});
</script>

{% endblock extrahead%}

{% block tela %}
<h1 align="center">Os Indicados</h1>
<p align="center"><img src="/osindicadosmedia/img/logo.png"/></p>
<div id="erro" style="color: red">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{error}}</div>
<form action="../config/" method="post">
{% csrf_token %}

<table align="center" border="0" cellpadding="3">
	<tr>
		<td><input style="color: #B1FB17; font-size: 20px;" type="submit" value="Iniciar Partida">
		</td>
		<td><a href="../ranking/">Ver Ranking</a>
		</td>
		<td><a href="../comojogar/">Como Jogar</a><br>
		</td>
	</tr>
</table>

{% endblock tela %}

{% block sidebar %}
	<table style="font-size: small;" align="center">
		<tr><td>
	{% for tema in temas %}
		<input type="checkbox" name="temas" value="{{tema}}" class="check" id="{{tema}}" checked/><label for="{{tema}}" class="temaselecionado">{{tema}}</label><br/>
		</td></tr><tr><td>

	{% endfor %}
	</td></tr>
		</table>
{% endblock sidebar%}

{% block footer %}
Dificuldade:
<input type="hidden" name="dificuldade" value='0' id="dificuldade"/>
<table>
 <tr><td><div id="lefclick" onclick="javascript: selectDifi('left');"><img src="/osindicadosmedia/img/seta1.png" style="cursor:pointer"> </div></td>
	<td><input type="text" name="listdificuldades" value="Amador" id="listdificuldades" size="10"/></td>
    <td><div id="rightclick" onclick="javascript: selectDifi('right');"><img src="/osindicadosmedia/img/seta2.png" style="cursor:pointer"> </div></td></tr>
</table>
</form>
{% endblock%}


osindicados/templates/jogo/erro.html
{% extends "jogo/basedesign.html" %}

{% block extrahead %}
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script type="text/javascript">
$(function(){
	$("a").button();
})
</script>
<style type="text/css">
#background{
	position: absolute;
	left: 10%;
	/* TODO: Mudar os tamanhos quando mudar a imagem*/
	width: 1000px;
	height: 711px;
	background-image: url("/osindicadosmedia/img/chuvisco.png");
	background-repeat: no-repeat;
	}
</style>
{% endblock extrahead %}

{% block tela %}


<div align="center">
<br/><br/><br/>
<img alt="você perdeu" src="/osindicadosmedia/img/gameover.png" width="250px"> <br/>
<br/><br/><br/>
<a href="../config/">Voltar para Tela Inicial</a>
</div>
{% endblock tela %}

osindicados/templates/jogo/ganhou.html
{% extends "jogo/basedesign.html" %}

{% block extrahead %}
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<style type="text/css">
#background{
	position: absolute;
	left: 10%;
	/* TODO: Mudar os tamanhos quando mudar a imagem*/
	width: 1000px;
	height: 711px;
	background-image: url("/osindicadosmedia/img/tv.png");
	background-repeat: no-repeat;
	}
</style>
{% endblock extrahead %}

{% block tela %}



<div align="center">
<br>
<img alt="voce ganhou" src="/osindicadosmedia/img/win.jpg" width="250px"> <br/>

<table>
	<tr>
		<TD ALIGN="left"><h1>Voc&ecirc; ganhou! <img alt="voce perdeu" src="/osindicadosmedia/img/trophy.gif"></h1>
		</td>
	</tr>
	<tr>
		<TD ALIGN="left">Deseja entrar para o ranking dos Indicados?<br><br>
		</td>
	</tr>
	<tr>
		<TD ALIGN="left">Se sim, insira seu nome aqui:
		</td>
	</tr>
	<tr>
		<TD ALIGN="left">
			<form name="entrarRanking_frm" method="post" action="../entrarRanking/">
				{% csrf_token %}
				<input type="text" name="nomeUsuario"/>
				<input type="submit" value="Entrar para o ranking!"/>
			</form>
		</TD>
	</tr>
	<tr>
		<TD ALIGN="left">Se n&atilde;o, clique <a href="../config/">aqui</a> para voltar &agrave; tela inicial.
		</td>
	</tr>
</table>

</div>
{% endblock tela %}



osindicados/templates/jogo/index.html
<h1> Lista de Temas </h1>

{% for entry in list_tema_qntd %}
  {{ entry.0 }} ( {{ entry.1  }} ) <br/>
{% endfor %}


<h1> Lista de Perguntas </h1>

{% for pergunta in perguntas %}

assunto: {{ pergunta.idAssunto }} - dificuldade: {{pergunta.dificuldade}} ({{pergunta.get_dificuldade_display}}) <br/>

  {{ pergunta.enunciado }} <br/>

  <ul>
    <li>{{ pergunta.altCorreta }}</li>
    <li>{{ pergunta.altIncorreta1 }}</li>
    <li>{{ pergunta.altIncorreta2 }}</li>
    <li>{{ pergunta.altIncorreta3 }}</li>
    <li>{{ pergunta.altIncorreta4 }}</li>
  </ul>

{% endfor %}